name: CrystalQuest
main: nl.SugCube.CrystalQuest.CrystalQuest
version: '0.4'
authors: [MrSugarCaney]
softdepend: [Multiverse-Core]
description: >
             The battle for the crystals!
commands:
  cq:
    description: Main command of CrystalQuest-plugin.