name: CrystalQuest
main: nl.SugCube.CrystalQuest.CrystalQuest
version: '0.2'
authors: [MrSugarCaney]
description: >
             The battle for the crystals!
commands:
  cq:
    description: Main command of CrystalQuest-plugin.